Bugfix update connect vraserver function
jakkulabs/PowervRA pull request #255
Opened 2021-03-22 01:00 UTC by Stevio54

I have a new update to the connect commandlet. I have removed the need for -UserAttribute, simply by handling a 400 error and trying a second time by tacking that @Domain portion of the username back on. This makes this issue transparent to the user.

I have also added a step where after using the CSP login endpoint, I then pass its refresh token to the IaaS Login API (documented in 8.3 release notes as the desired process). This is all tested against 8.2 and 8.3 versions of vRA.

2021-03-22 18:01 UTC, jonathanmedd requested changes

2021-04-12 10:40 UTC, Stevio54 commented on .vscode/settings.json
> +{
latest commit, this is removed.

2021-04-12 10:40 UTC, Stevio54 commented on src/Functions/Public/Connect-vRAServer.ps1
> +                    Body = ($RawBody | ConvertTo-Json)
latest commit these are removed.

2021-04-12 10:40 UTC, Stevio54 commented on src/Functions/Public/Connect-vRAServer.ps1
> +                    if ($_.Exception.Response.StatusCode -eq "BadRequest" -and $null -ne $AlternateJson) {
latest commit this is removed.

2021-04-12 10:41 UTC, Stevio54 commented on src/Functions/Public/Connect-vRAServer.ps1
> +                        $Params.Body = ($RawBody | ConvertTo-Json)
latest commit these are removed.

2021-04-12 11:24 UTC, jonathanmedd approved these changes
LGTM

2021-04-12 14:25 UTC, merged